using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TravelApp.Services.Trip.Models
{
    /// <summary>
    /// Represents a travel trip planned by a user, with optional AI-generated day-by-day itineraries.
    /// </summary>
    public class Trip
    {
        /// <summary>Gets or sets the unique identifier for this trip.</summary>
        public int Id { get; set; }

        /// <summary>Gets or sets the ID of the user who owns this trip.</summary>
        public int UserId { get; set; }

        /// <summary>Gets or sets the destination city or country for the trip.</summary>
        [Required]
        public string Destination { get; set; } = "";

        /// <summary>Gets or sets the planned start date of the trip.</summary>
        public DateTime StartDate { get; set; }

        /// <summary>Gets or sets the planned end date of the trip.</summary>
        public DateTime EndDate { get; set; }

        /// <summary>Gets or sets the UTC timestamp when this trip was created.</summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>Gets or sets the collection of day-by-day itinerary items for this trip.</summary>
        public ICollection<Itinerary> Itineraries { get; set; } = new List<Itinerary>();
    }

    /// <summary>
    /// Represents a single day's planned activity within a <see cref="Trip"/>.
    /// Generated by the Gemini AI service based on the trip's destination and user preferences.
    /// </summary>
    public class Itinerary
    {
        /// <summary>Gets or sets the unique identifier for this itinerary item.</summary>
        public int Id { get; set; }

        /// <summary>Gets or sets the ID of the parent trip this itinerary belongs to.</summary>
        public int TripId { get; set; }

        /// <summary>Gets or sets the parent trip navigation property.</summary>
        [ForeignKey("TripId")]
        public Trip Trip { get; set; } = null!;

        /// <summary>Gets or sets the day number within the trip (e.g., Day 1, Day 2).</summary>
        public int DayNumber { get; set; }

        /// <summary>Gets or sets a description of the planned activity for this day.</summary>
        [Required, Column(TypeName = "nvarchar(max)")]
        public string Activity { get; set; } = "";

        /// <summary>Gets or sets the location or venue for this day's activity.</summary>
        [MaxLength(200)]
        public string Location { get; set; } = "";
    }
}
