// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApp.Services.Hotel.Data;

#nullable disable

namespace TravelApp.Services.Hotel.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20260409092644_AddOwnershipAndApprovalStatus")]
    partial class AddOwnershipAndApprovalStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelApp.Services.Hotel.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StarRating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "2 Sardar Patel Marg, New Delhi",
                            Amenities = "Pool,Spa,Gym,Restaurant,Bar,WiFi",
                            ApprovalStatus = "Approved",
                            City = "Delhi",
                            Description = "Iconic luxury hotel in the heart of Delhi",
                            Name = "The Taj Palace",
                            OwnerEmail = "",
                            OwnerId = 0,
                            OwnerName = "",
                            StarRating = 5.0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Marine Lines, Mumbai",
                            Amenities = "Pool,Restaurant,WiFi,Gym",
                            ApprovalStatus = "Approved",
                            City = "Mumbai",
                            Description = "Stunning sea-view suites in South Mumbai",
                            Name = "Marina Bay Suites",
                            OwnerEmail = "",
                            OwnerId = 0,
                            OwnerName = "",
                            StarRating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Calangute Beach, North Goa",
                            Amenities = "Pool,Beach Access,Spa,Restaurant,Bar,WiFi",
                            ApprovalStatus = "Approved",
                            City = "Goa",
                            Description = "Beachfront resort with lush tropical gardens",
                            Name = "Spice Garden Resort",
                            OwnerEmail = "",
                            OwnerId = 0,
                            OwnerName = "",
                            StarRating = 4.0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Old Manali Road, Manali",
                            Amenities = "Restaurant,WiFi,Bonfire",
                            ApprovalStatus = "Approved",
                            City = "Manali",
                            Description = "Cozy mountain hotel with panoramic Himalayan views",
                            Name = "Himalayan Retreat",
                            OwnerEmail = "",
                            OwnerId = 0,
                            OwnerName = "",
                            StarRating = 3.0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Pink City, Jaipur",
                            Amenities = "Pool,Spa,Restaurant,Cultural Shows,WiFi",
                            ApprovalStatus = "Approved",
                            City = "Jaipur",
                            Description = "Traditional Rajasthani haveli turned luxury hotel",
                            Name = "Heritage Haveli",
                            OwnerEmail = "",
                            OwnerId = 0,
                            OwnerName = "",
                            StarRating = 5.0
                        });
                });

            modelBuilder.Entity("TravelApp.Services.Hotel.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApprovalStatus = "Approved",
                            Description = "Spacious room with city view",
                            HotelId = 1,
                            IsAvailable = true,
                            MaxOccupancy = 2,
                            PricePerNight = 12000m,
                            Type = "Deluxe King"
                        },
                        new
                        {
                            Id = 2,
                            ApprovalStatus = "Approved",
                            Description = "Top-floor suite with panoramic Delhi views",
                            HotelId = 1,
                            IsAvailable = true,
                            MaxOccupancy = 4,
                            PricePerNight = 45000m,
                            Type = "Presidential Suite"
                        },
                        new
                        {
                            Id = 3,
                            ApprovalStatus = "Approved",
                            Description = "Room with stunning Arabian Sea views",
                            HotelId = 2,
                            IsAvailable = true,
                            MaxOccupancy = 2,
                            PricePerNight = 8500m,
                            Type = "Sea View Double"
                        },
                        new
                        {
                            Id = 4,
                            ApprovalStatus = "Approved",
                            Description = "Comfortable twin room",
                            HotelId = 2,
                            IsAvailable = true,
                            MaxOccupancy = 2,
                            PricePerNight = 5500m,
                            Type = "Standard Twin"
                        },
                        new
                        {
                            Id = 5,
                            ApprovalStatus = "Approved",
                            Description = "Private cottage steps from the beach",
                            HotelId = 3,
                            IsAvailable = true,
                            MaxOccupancy = 2,
                            PricePerNight = 9000m,
                            Type = "Beach Cottage"
                        },
                        new
                        {
                            Id = 6,
                            ApprovalStatus = "Approved",
                            Description = "Suite overlooking tropical gardens",
                            HotelId = 3,
                            IsAvailable = true,
                            MaxOccupancy = 3,
                            PricePerNight = 6500m,
                            Type = "Garden Suite"
                        },
                        new
                        {
                            Id = 7,
                            ApprovalStatus = "Approved",
                            Description = "Cozy room with Himalayan vistas",
                            HotelId = 4,
                            IsAvailable = true,
                            MaxOccupancy = 2,
                            PricePerNight = 3500m,
                            Type = "Mountain View Room"
                        },
                        new
                        {
                            Id = 8,
                            ApprovalStatus = "Approved",
                            Description = "Opulent Rajasthani-themed royal suite",
                            HotelId = 5,
                            IsAvailable = true,
                            MaxOccupancy = 2,
                            PricePerNight = 18000m,
                            Type = "Royal Suite"
                        });
                });

            modelBuilder.Entity("TravelApp.Services.Hotel.Models.Room", b =>
                {
                    b.HasOne("TravelApp.Services.Hotel.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("TravelApp.Services.Hotel.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
